# Generated by Django 6.0.2 on 2026-03-03 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0003_alter_organization_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=255, verbose_name="ФИО или Ник"),
                ),
                (
                    "author_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email для уведомлений",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Заголовок вопроса"),
                ),
                ("content", models.TextField(verbose_name="Текст вопроса")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В обработке"),
                            ("has_suggestions", "Есть предложения"),
                            ("has_best", "Есть лучшее"),
                            ("closed", "Закрыт"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения статуса"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата взятия в обработку"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
                (
                    "suggestions_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество предложений"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Одобрено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто взял в обработку",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=255, verbose_name="ФИО или Ник"),
                ),
                (
                    "author_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email для уведомлений",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст предложения")),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="Лайки"),
                ),
                (
                    "dislikes_count",
                    models.PositiveIntegerField(default=0, verbose_name="Дизлайки"),
                ),
                (
                    "reactions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Реакции (эмоджи)"
                    ),
                ),
                (
                    "is_best",
                    models.BooleanField(
                        default=False, verbose_name="Лучшее предложение"
                    ),
                ),
                (
                    "marked_as_best_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отметки лучшим"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Одобрено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отметил лучшим",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="questions.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
                "ordering": ["-is_best", "-likes_count", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_session",
                    models.CharField(max_length=255, verbose_name="Сессия голосующего"),
                ),
                (
                    "vote",
                    models.SmallIntegerField(
                        choices=[(1, "Лайк"), (-1, "Дизлайк")], verbose_name="Голос"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата голоса"),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="questions.suggestion",
                        verbose_name="Предложение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Голос",
                "verbose_name_plural": "Голоса",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=255, verbose_name="ФИО или Ник"),
                ),
                (
                    "author_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email для уведомлений",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст комментария")),
                ("object_id", models.PositiveIntegerField(verbose_name="ID объекта")),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="Лайки"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Одобрено"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удален"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="questions.comment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="questions_c_content_226651_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="questions_c_created_58df16_idx"
                    ),
                    models.Index(
                        fields=["is_approved"], name="questions_c_is_appr_cee6c4_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["status"], name="questions_q_status_fca2ef_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["created_at"], name="questions_q_created_d1d888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["organization"], name="questions_q_organiz_280cf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["suggestion", "voter_session"],
                name="questions_v_suggest_31d986_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("suggestion", "voter_session")},
        ),
    ]
