# Generated by Django 6.0.2 on 2026-03-04 11:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Текст вопроса"),
        ),
    ]
