# Generated by Django 6.0.2 on 2026-03-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organization_status"),
        ("questions", "0002_alter_question_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions",
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
    ]
