# Generated by Django 6.0.2 on 2026-03-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_suggestion_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author_email",
        ),
    ]
