# Generated by Django 6.0.2 on 2026-03-16 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("questions", "0004_remove_comment_author_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="likes_count",
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_deleted"], name="questions_c_is_dele_336fba_idx"
            ),
        ),
    ]
