#!/bin/bash

set -o errexit

set -o nounset

# watchmedo auto-restart -d witwall/ -p "*.py" -- celery -A witwall worker --loglevel=info

# Просто запускаем worker от celeryuser
exec celery -A witwall worker --loglevel=info
