#!/bin/bash

set -o errexit

set -o nounset

# watchmedo auto-restart -d wall/ -p "*.py" -- celery -A wall worker --loglevel=info

# Просто запускаем worker от celeryuser
exec celery -A wall worker --loglevel=info
