# Generated by Django 6.0.2 on 2026-03-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('full_name', models.TextField(verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=500, verbose_name='Краткое наименование')),
                ('address_raw', models.TextField(verbose_name='Адрес (строка)')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=300, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'indexes': [models.Index(fields=['inn'], name='organizatio_inn_dc47b1_idx'), models.Index(fields=['short_name'], name='organizatio_short_n_569325_idx')],
            },
        ),
    ]
