# Generated by Django 6.0.2 on 2026-03-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Типы организаций',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты (широта, долгота)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organizationtype', verbose_name='Тип организации'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['district'], name='organizatio_distric_3086df_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_5ff202_idx'),
        ),
    ]
