# Generated by Django 6.0.2 on 2026-03-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationtype_organization_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Действующая'), ('LIQUIDATING', 'Ликвидируется'), ('LIQUIDATED', 'Ликвидирована'), ('REORGANIZING', 'В процессе присоединения к другому юрлицу, с последующей ликвидацией')], max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
